version: 2

sources:
  - name: dbt
    tables:
      - name: raw_gz_sales
      - name: raw_gz_ship
      - name: raw_gz_product 
models:
  - name: int_sales_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: products_id
        description: products key
        tests:
          - not_null
      - name: margin
        description: Margin = Revenue - Purchase_cost
        tests:
          - not_null
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null
    tests:
     - unique:
        column_name: "(orders_id || '-' || products_id)"

